// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    partial class MigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.DBModels.Common.ApplicationLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Image")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRTL")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Image");

                    b.HasIndex("Fk_Tenant");

                    b.ToTable("ApplicationLanguage", "Common");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant");

                    b.ToTable("Attachment", "Common");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Module")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant", "Module", "Key")
                        .IsUnique()
                        .HasFilter("[Fk_Tenant] IS NOT NULL");

                    b.ToTable("Configuration", "Common");
                });

            modelBuilder.Entity("Entities.DBModels.Common.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant", "Name")
                        .IsUnique()
                        .HasFilter("[Fk_Tenant] IS NOT NULL");

                    b.ToTable("EmailTemplate", "Common");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Image")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Image");

                    b.HasIndex("Fk_Tenant", "EntityType", "Name")
                        .IsUnique()
                        .HasFilter("[Fk_Tenant] IS NOT NULL");

                    b.ToTable("Lookup", "Common");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityType = 1,
                            IsActive = true,
                            Name = "Male",
                            SoftDelete = false,
                            Sort = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 2,
                            EntityType = 1,
                            IsActive = true,
                            Name = "Female",
                            SoftDelete = false,
                            Sort = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 3,
                            EntityType = 1,
                            IsActive = true,
                            Name = "Unknown",
                            SoftDelete = false,
                            Sort = 0
                        });
                });

            modelBuilder.Entity("Entities.DBModels.Common.LookupLang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Source")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Source")
                        .IsUnique();

                    b.ToTable("LookupLang", "Common");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RowText")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant", "LanguageCode", "ApplicationEnum", "RowText")
                        .IsUnique()
                        .HasFilter("[Fk_Tenant] IS NOT NULL");

                    b.ToTable("Translation", "Common");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<int>("Fk_User")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant");

                    b.HasIndex("Fk_User")
                        .IsUnique();

                    b.ToTable("Administrator", "Permission");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Functionality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_Resource")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<string>("FunctionalityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Resource");

                    b.HasIndex("Fk_Tenant");

                    b.ToTable("Functionality", "Permission");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant");

                    b.ToTable("Resource", "Permission");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant", "Name")
                        .IsUnique()
                        .HasFilter("[Fk_Tenant] IS NOT NULL");

                    b.ToTable("Role", "Permission");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Functionality")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Role")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Functionality");

                    b.HasIndex("Fk_Role");

                    b.HasIndex("Fk_Tenant");

                    b.ToTable("RolePermission", "Permission");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Role")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<int>("Fk_User")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Role");

                    b.HasIndex("Fk_Tenant");

                    b.HasIndex("Fk_User", "Fk_Role")
                        .IsUnique();

                    b.ToTable("UserRole", "Permission");
                });

            modelBuilder.Entity("Entities.DBModels.Tenants.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenant", "Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Tenants.TenantSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant", "Key")
                        .IsUnique();

                    b.ToTable("TenantSetting", "Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Users.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirebaseToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Fk_User")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_User", "FirebaseToken")
                        .IsUnique()
                        .HasFilter("[FirebaseToken] IS NOT NULL");

                    b.ToTable("Device", "User");
                });

            modelBuilder.Entity("Entities.DBModels.Users.ExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<int>("Fk_User")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_User");

                    b.HasIndex("Fk_Tenant", "ProviderKey")
                        .IsUnique()
                        .HasFilter("[Fk_Tenant] IS NOT NULL");

                    b.ToTable("ExternalLogin", "User");
                });

            modelBuilder.Entity("Entities.DBModels.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<int>("Fk_User")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_User");

                    b.HasIndex("Fk_Tenant", "Token")
                        .IsUnique();

                    b.ToTable("RefreshToken", "User");
                });

            modelBuilder.Entity("Entities.DBModels.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FK_Image")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginFailedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonePrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkAddress_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkAddress_District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkAddress_Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FK_Image");

                    b.HasIndex("Fk_Tenant", "UserName")
                        .IsUnique()
                        .HasFilter("[SoftDelete] = 0");

                    b.ToTable("User", "User");
                });

            modelBuilder.Entity("Entities.DBModels.Users.Verification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("CreatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fk_Tenant")
                        .HasColumnType("int");

                    b.Property<int>("Fk_User")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByDeviceID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Tenant");

                    b.HasIndex("Fk_User");

                    b.ToTable("Verification", "User");
                });

            modelBuilder.Entity("Entities.DBModels.Common.ApplicationLanguage", b =>
                {
                    b.HasOne("Entities.DBModels.Common.Attachment", "Image")
                        .WithMany()
                        .HasForeignKey("Fk_Image")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Image");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Attachment", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Configuration", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Common.EmailTemplate", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Lookup", b =>
                {
                    b.HasOne("Entities.DBModels.Common.Attachment", "Image")
                        .WithMany()
                        .HasForeignKey("Fk_Image")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Image");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Common.LookupLang", b =>
                {
                    b.HasOne("Entities.DBModels.Common.Lookup", "Source")
                        .WithOne("LookupLang")
                        .HasForeignKey("Entities.DBModels.Common.LookupLang", "Fk_Source")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Translation", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Administrator", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DBModels.Users.User", "User")
                        .WithOne("Administrator")
                        .HasForeignKey("Entities.DBModels.Permission.Administrator", "Fk_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Functionality", b =>
                {
                    b.HasOne("Entities.DBModels.Permission.Resource", "Resource")
                        .WithMany("Functionalities")
                        .HasForeignKey("Fk_Resource")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Resource");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Resource", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Role", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.RolePermission", b =>
                {
                    b.HasOne("Entities.DBModels.Permission.Functionality", "Functionality")
                        .WithMany("RolePermissions")
                        .HasForeignKey("Fk_Functionality")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.DBModels.Permission.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("Fk_Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Functionality");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.UserRole", b =>
                {
                    b.HasOne("Entities.DBModels.Permission.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("Fk_Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.DBModels.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("Fk_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.DBModels.Tenants.TenantSetting", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Users.Device", b =>
                {
                    b.HasOne("Entities.DBModels.Users.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("Fk_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.DBModels.Users.ExternalLogin", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DBModels.Users.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("Fk_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.DBModels.Users.RefreshToken", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.DBModels.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("Fk_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.DBModels.Users.User", b =>
                {
                    b.HasOne("Entities.DBModels.Common.Attachment", "Image")
                        .WithMany()
                        .HasForeignKey("FK_Image")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.DBModels.Users.Verification", b =>
                {
                    b.HasOne("Entities.DBModels.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Fk_Tenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.DBModels.Users.User", "User")
                        .WithMany("Verifications")
                        .HasForeignKey("Fk_User")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.DBModels.Common.Lookup", b =>
                {
                    b.Navigation("LookupLang");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Functionality", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Resource", b =>
                {
                    b.Navigation("Functionalities");
                });

            modelBuilder.Entity("Entities.DBModels.Permission.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Entities.DBModels.Users.User", b =>
                {
                    b.Navigation("Administrator");

                    b.Navigation("Devices");

                    b.Navigation("ExternalLogins");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");

                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
